Unit Seawar4;
interface
uses Crt,Graph,seawar1;
Procedure Check51;
Procedure Check52;
Procedure Check53;
Procedure Check54;
Procedure Check55;
Procedure Check56;
Procedure Check57;
procedure Check58;
Procedure Check59;
Procedure Check510;
Procedure Check41;
Procedure Check42;
Procedure Check43;
Procedure Check44;
Procedure Check45;
Procedure Check46;
Procedure Check47;
Procedure Check48;
Procedure Check49;
Procedure Check410;
Procedure Check61;
Procedure Check62;
Procedure Check63;
Procedure Check64;
Procedure Check65;
Procedure Check66;
Procedure Check67;
Procedure Check68;
Procedure Check69;
Procedure Check610;
Procedure Check71;
Procedure Check72;
Procedure Check73;
Procedure Check74;
Procedure Check75;
Procedure Check76;
Procedure Check77;
Procedure Check78;
Procedure Check81;
Procedure Check82;
Procedure Check83;
Procedure Check84;
Procedure Check85;
Procedure Check86;
Procedure Check87;
Procedure Check88;
Procedure Check91;
Procedure Check92;
Procedure Check93;
Procedure Check94;
Procedure Check95;
Procedure Check96;
Procedure Check97;
Procedure Check98;
implementation
  uses seawar3;
  procedure Check91;
 begin
   if bh1x = pos14x then
   if bh1y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,15,'warning error in first loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,15,'First loop Ok');
   Setcolor(White); end;   end;


  procedure Check81;
begin
   if bg1x = pos13x then
   if bg1y = pos13y then
   begin eror := 'Des' ; end;

   if bg1x = pos14x then
   if bg1y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,15,'warning error in first loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,15,'First loop Ok');
   Setcolor(White); end;   end;


  procedure Check71;
begin
   if bf1x = pos12x then
   if bf1y = pos12y then
   begin eror := 'Des'; end;

   if bf1x = pos13x then
   if bf1y = pos13y then
   begin eror := 'Des' ; end;

   if bf1x = pos14x then
   if bf1y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,15,'warning error in first loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,15,'First loop Ok');
   Setcolor(White); end;   end;

  procedure Check61;
begin
   if be1x = pos11x then
   if be1y = pos11y then
   begin eror := 'Des' ; end;

   if be1x = pos12x then
   if be1y = pos12y then
   begin eror := 'Des'; end;

   if be1x = pos13x then
   if be1y = pos13y then
   begin eror := 'Des' ; end;

   if be1x = pos14x then
   if be1y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,15,'warning error in first loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,15,'First loop Ok');
   Setcolor(White); end;   end;


  procedure Check51;
begin
   if pos23 = 1 then begin
   if bd1x = pos23x then
   if bd1y = pos23y then
   begin eror := 'Des'; end;

   if bd1x = pos23x + 25 then
   if bd1y = pos23y then
   begin eror := 'Des';end;end;

      if pos23 = 2 then begin
   if bd1x = pos23x then
   if bd1y = pos23y then
   begin eror := 'Des'; end;

   if bd1x = pos23x then
   if bd1y = pos23y + 25 then
   begin eror := 'Des';end;end;


   if bd1x = pos11x then
   if bd1y = pos11y then
   begin eror := 'Des' ; end;

   if bd1x = pos12x then
   if bd1y = pos12y then
   begin eror := 'Des'; end;

   if bd1x = pos13x then
   if bd1y = pos13y then
   begin eror := 'Des' ; end;

   if bd1x = pos14x then
   if bd1y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,15,'warning error in first loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,15,'First loop Ok');
   Setcolor(White); end;   end;


  procedure Check41;
begin
   if pos22 = 1 then begin
   if bc1x = pos22x then
   if bc1y = pos22y then
   begin eror := 'Des' ; end;

   if bc1x = pos22x + 25 then
   if bc1y = pos22y then
   begin eror := 'Des' ; end; end;

     if pos22 = 2 then begin
   if bc1x = pos22x then
   if bc1y = pos22y then
   begin eror := 'Des' ; end;

   if bc1x = pos22x  then
   if bc1y = pos22y + 25then
   begin eror := 'Des' ; end; end;

   if pos23 = 1 then begin
   if bc1x = pos23x then
   if bc1y = pos23y then
   begin eror := 'Des'; end;

   if bc1x = pos23x + 25 then
   if bc1y = pos23y then
   begin eror := 'Des';end;end;

      if pos23 = 2 then begin
   if bc1x = pos23x then
   if bc1y = pos23y then
   begin eror := 'Des'; end;

   if bc1x = pos23x then
   if bc1y = pos23y + 25 then
   begin eror := 'Des';end;end;


   if bc1x = pos11x then
   if bc1y = pos11y then
   begin eror := 'Des' ; end;

   if bc1x = pos12x then
   if bc1y = pos12y then
   begin eror := 'Des'; end;

   if bc1x = pos13x then
   if bc1y = pos13y then
   begin eror := 'Des' ; end;

   if bc1x = pos14x then
   if bc1y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,15,'warning error in first loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,15,'First loop Ok');
   Setcolor(White); end;   end;

   procedure Check92;
   begin
   if bh2x = pos14x then
   if bh2y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,25,'warning error in second loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,25,'Second loop Ok');
   Setcolor(White); end; end;


   procedure Check82;
   begin
   if bg2x = pos13x then
   if bg2y = pos13y then
   begin eror := 'Des' ; end;

   if bg2x = pos14x then
   if bg2y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,25,'warning error in second loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,25,'Second loop Ok');
   Setcolor(White); end; end;


   procedure Check72;
   begin
   if bf2x = pos12x then
   if bf2y = pos12y then
   begin eror := 'Des'; end;

   if bf2x = pos13x then
   if bf2y = pos13y then
   begin eror := 'Des' ; end;

   if bf2x = pos14x then
   if bf2y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,25,'warning error in second loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,25,'Second loop Ok');
   Setcolor(White); end; end;


   procedure Check62;
    begin
   if be2x = pos11x then
   if be2y = pos11y then
   begin eror := 'Des' ; end;

   if be2x = pos12x then
   if be2y = pos12y then
   begin eror := 'Des'; end;

   if be2x = pos13x then
   if be2y = pos13y then
   begin eror := 'Des' ; end;

   if be2x = pos14x then
   if be2y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,25,'warning error in second loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,25,'Second loop Ok');
   Setcolor(White); end; end;

   procedure Check52;
    begin
   if pos23 = 1 then begin
   if bd2x = pos23x then
   if bd2y = pos23y then
   begin eror := 'Des'; end;

   if bd2x = pos23x + 25 then
   if bd2y = pos23y then
   begin eror := 'Des';end; end;

    if pos23 = 2 then begin
   if bd2x = pos23x then
   if bd2y = pos23y then
   begin eror := 'Des'; end;

   if bd2x = pos23x then
   if bd2y = pos23y + 25 then
   begin eror := 'Des';end; end;

   if bd2x = pos11x then
   if bd2y = pos11y then
   begin eror := 'Des' ; end;

   if bd2x = pos12x then
   if bd2y = pos12y then
   begin eror := 'Des'; end;

   if bd2x = pos13x then
   if bd2y = pos13y then
   begin eror := 'Des' ; end;

   if bd2x = pos14x then
   if bd2y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,25,'warning error in second loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,25,'Second loop Ok');
   Setcolor(White); end; end;

    procedure Check42;
  begin
  if pos22 = 1 then begin
   if bc2x = pos22x then
   if bc2y = pos22y then
   begin eror := 'Des' ; end;

   if bc2x = pos22x + 25 then
   if bc2y = pos22y then
   begin eror := 'Des' ; end; end;

   if pos22 = 2 then begin
   if bc2x = pos22x then
   if bc2y = pos22y then
   begin eror := 'Des' ; end;

   if bc2x = pos22x then
   if bc2y = pos22y + 25then
   begin eror := 'Des' ; end; end;

   if pos23 = 1 then begin
   if bc2x = pos23x then
   if bc2y = pos23y then
   begin eror := 'Des'; end;

   if bc2x = pos23x + 25 then
   if bc2y = pos23y then
   begin eror := 'Des';end; end;

    if pos23 = 2 then begin
   if bc2x = pos23x then
   if bc2y = pos23y then
   begin eror := 'Des'; end;

   if bc2x = pos23x then
   if bc2y = pos23y + 25 then
   begin eror := 'Des';end; end;

   if bc2x = pos11x then
   if bc2y = pos11y then
   begin eror := 'Des' ; end;

   if bc2x = pos12x then
   if bc2y = pos12y then
   begin eror := 'Des'; end;

   if bc2x = pos13x then
   if bc2y = pos13y then
   begin eror := 'Des' ; end;

   if bc2x = pos14x then
   if bc2y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,25,'warning error in second loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,25,'Second loop Ok');
   Setcolor(White); end; end;

   procedure Check93;
   begin
   if bh3x = pos14x then
   if bh3y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,35,'warning error in third loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,35,'third loop Ok');
   Setcolor(White); end; end;

   procedure Check83;
 begin
   if bg3x = pos13x then
   if bg3y = pos13y then
   begin eror := 'Des' ; end;

   if bg3x = pos14x then
   if bg3y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,35,'warning error in third loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,35,'third loop Ok');
   Setcolor(White); end; end;


   procedure Check73;
 begin
   if bf3x = pos12x then
   if bf3y = pos12y then
   begin eror := 'Des'; end;

   if bf3x = pos13x then
   if bf3y = pos13y then
   begin eror := 'Des' ; end;

   if bf3x = pos14x then
   if bf3y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,35,'warning error in third loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,35,'third loop Ok');
   Setcolor(White); end; end;


   procedure Check63;
 begin
   if be3x = pos11x then
   if be3y = pos11y then
   begin eror := 'Des' ; end;

   if be3x = pos12x then
   if be3y = pos12y then
   begin eror := 'Des'; end;

   if be3x = pos13x then
   if be3y = pos13y then
   begin eror := 'Des' ; end;

   if be3x = pos14x then
   if be3y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,35,'warning error in third loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,35,'third loop Ok');
   Setcolor(White); end; end;

   procedure Check53;
 begin
   if pos23 = 1 then begin
   if bd3x = pos23x then
   if bd3y = pos23y then
   begin eror := 'Des'; end;

   if bd3x = pos23x + 25 then
   if bd3y = pos23y then
   begin eror := 'Des';end; end;

   if pos23 = 2 then begin
   if bd3x = pos23x then
   if bd3y = pos23y then
   begin eror := 'Des'; end;

   if bd3x = pos23x then
   if bd3y = pos23y + 25 then
   begin eror := 'Des';end; end;

   if bd3x = pos11x then
   if bd3y = pos11y then
   begin eror := 'Des' ; end;

   if bd3x = pos12x then
   if bd3y = pos12y then
   begin eror := 'Des'; end;

   if bd3x = pos13x then
   if bd3y = pos13y then
   begin eror := 'Des' ; end;

   if bd3x = pos14x then
   if bd3y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,35,'warning error in third loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,35,'third loop Ok');
   Setcolor(White); end; end;
   procedure Check43;
 begin
  if pos22 = 1 then begin
   if bc3x = pos22x then
   if bc3y = pos22y then
   begin eror := 'Des' ; end;

   if bc3x = pos22x + 25 then
   if bc3y = pos22y then
   begin eror := 'Des' ; end; end;

   if pos22 = 2 then begin
   if bc3x = pos22x then
   if bc3y = pos22y then
   begin eror := 'Des' ; end;

   if bc3x = pos22x then
   if bc3y = pos22y + 25then
   begin eror := 'Des' ; end; end;

   if pos23 = 1 then begin
   if bc3x = pos23x then
   if bc3y = pos23y then
   begin eror := 'Des'; end;

   if bc3x = pos23x + 25 then
   if bc3y = pos23y then
   begin eror := 'Des';end; end;

   if pos23 = 2 then begin
   if bc3x = pos23x then
   if bc3y = pos23y then
   begin eror := 'Des'; end;

   if bc3x = pos23x then
   if bc3y = pos23y + 25 then
   begin eror := 'Des';end; end;

   if bc3x = pos11x then
   if bc3y = pos11y then
   begin eror := 'Des' ; end;

   if bc3x = pos12x then
   if bc3y = pos12y then
   begin eror := 'Des'; end;

   if bc3x = pos13x then
   if bc3y = pos13y then
   begin eror := 'Des' ; end;

   if bc3x = pos14x then
   if bc3y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,35,'warning error in third loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,35,'third loop Ok');
   Setcolor(White); end; end;

   procedure Check94;
  begin
   if bh4x = pos14x then
   if bh4y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,45,'warning error in four loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,45,'four loop Ok');
   Setcolor(White); end; end;

   procedure Check84;
  begin
   if bg4x = pos13x then
   if bg4y = pos13y then
   begin eror := 'Des' ; end;

   if bg4x = pos14x then
   if bg4y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,45,'warning error in four loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,45,'four loop Ok');
   Setcolor(White); end; end;

   procedure Check74;
 begin

   if bf4x = pos12x then
   if bf4y = pos12y then
   begin eror := 'Des'; end;

   if bf4x = pos13x then
   if bf4y = pos13y then
   begin eror := 'Des' ; end;

   if bf4x = pos14x then
   if bf4y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,45,'warning error in four loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,45,'four loop Ok');
   Setcolor(White); end; end;
   procedure check64;
 begin
   if be4x = pos11x then
   if be4y = pos11y then
   begin eror := 'Des' ; end;

   if be4x = pos12x then
   if be4y = pos12y then
   begin eror := 'Des'; end;

   if be4x = pos13x then
   if be4y = pos13y then
   begin eror := 'Des' ; end;

   if be4x = pos14x then
   if be4y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,45,'warning error in four loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,45,'four loop Ok');
   Setcolor(White); end; end;


   procedure Check54;
 begin
   if pos23 = 1 then begin
   if bd4x = pos23x then
   if bd4y = pos23y then
   begin eror := 'Des'; end;

   if bd4x = pos23x + 25 then
   if bd4y = pos23y then
   begin eror := 'Des';end; end;

   if pos23 = 2 then begin
   if bd4x = pos23x then
   if bd4y = pos23y then
   begin eror := 'Des'; end;

   if bd4x = pos23x then
   if bd4y = pos23y + 25 then
   begin eror := 'Des';end; end;

   if bd4x = pos11x then
   if bd4y = pos11y then
   begin eror := 'Des' ; end;

   if bd4x = pos12x then
   if bd4y = pos12y then
   begin eror := 'Des'; end;

   if bd4x = pos13x then
   if bd4y = pos13y then
   begin eror := 'Des' ; end;

   if bd4x = pos14x then
   if bd4y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,45,'warning error in four loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,45,'four loop Ok');
   Setcolor(White); end; end;


   procedure Check44;
 begin
 if pos22 = 1 then begin
   if bc4x = pos22x then
   if bc4y = pos22y then
   begin eror := 'Des' ; end;

   if bc4x = pos22x + 25 then
   if bc4y = pos22y then
   begin eror := 'Des' ; end; end;

   if pos22 = 2 then begin
   if bc4x = pos22x then
   if bc4y = pos22y then
   begin eror := 'Des' ; end;

   if bc4x = pos22x then
   if bc4y = pos22y + 25then
   begin eror := 'Des' ; end; end;

   if pos23 = 1 then begin
   if bc4x = pos23x then
   if bc4y = pos23y then
   begin eror := 'Des'; end;

   if bc4x = pos23x + 25 then
   if bc4y = pos23y then
   begin eror := 'Des';end; end;

   if pos23 = 2 then begin
   if bc4x = pos23x then
   if bc4y = pos23y then
   begin eror := 'Des'; end;

   if bc4x = pos23x then
   if bc4y = pos23y + 25 then
   begin eror := 'Des';end; end;

   if bc4x = pos11x then
   if bc4y = pos11y then
   begin eror := 'Des' ; end;

   if bc4x = pos12x then
   if bc4y = pos12y then
   begin eror := 'Des'; end;

   if bc4x = pos13x then
   if bc4y = pos13y then
   begin eror := 'Des' ; end;

   if bc4x = pos14x then
   if bc4y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,45,'warning error in four loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,45,'four loop Ok');
   Setcolor(White); end; end;

   procedure check95;
  begin
   if bh5x = pos14x then
   if bh5y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,55,'warning error in fifth loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,55,'fifth loop Ok');
   Setcolor(White); end; end;


   procedure Check85;
  begin
   if bg5x = pos13x then
   if bg5y = pos13y then
   begin eror := 'Des' ; end;

   if bg5x = pos14x then
   if bg5y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,55,'warning error in fifth loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,55,'fifth loop Ok');
   Setcolor(White); end; end;


   procedure Check75;
  begin
   if bf5x = pos12x then
   if bf5y = pos12y then
   begin eror := 'Des'; end;

   if bf5x = pos13x then
   if bf5y = pos13y then
   begin eror := 'Des' ; end;

   if bf5x = pos14x then
   if bf5y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,55,'warning error in fifth loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,55,'fifth loop Ok');
   Setcolor(White); end; end;

   procedure Check65;
  begin
   if be5x = pos11x then
   if be5y = pos11y then
   begin eror := 'Des' ; end;

   if be5x = pos12x then
   if be5y = pos12y then
   begin eror := 'Des'; end;

   if be5x = pos13x then
   if be5y = pos13y then
   begin eror := 'Des' ; end;

   if be5x = pos14x then
   if be5y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,55,'warning error in fifth loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,55,'fifth loop Ok');
   Setcolor(White); end; end;

   procedure Check55;
 begin
   if pos23 = 1 then begin
   if bd5x = pos23x then
   if bd5y = pos23y then
   begin eror := 'Des'; end;

   if bd5x = pos23x + 25 then
   if bd5y = pos23y then
   begin eror := 'Des';end; end;

   if pos23 = 2 then begin
   if bd5x = pos23x then
   if bd5y = pos23y then
   begin eror := 'Des'; end;

   if bd5x = pos23x then
   if bd5y = pos23y + 25 then
   begin eror := 'Des';end; end;

   if bd5x = pos11x then
   if bd5y = pos11y then
   begin eror := 'Des' ; end;

   if bd5x = pos12x then
   if bd5y = pos12y then
   begin eror := 'Des'; end;

   if bd5x = pos13x then
   if bd5y = pos13y then
   begin eror := 'Des' ; end;

   if bd5x = pos14x then
   if bd5y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,55,'warning error in fifth loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,55,'fifth loop Ok');
   Setcolor(White); end; end;

   procedure Check45;
 begin
  if pos22 = 1 then begin
   if bc5x = pos22x then
   if bc5y = pos22y then
   begin eror := 'Des' ; end;

   if bc5x = pos22x + 25 then
   if bc5y = pos22y then
   begin eror := 'Des' ; end; end;

   if pos22 = 2 then begin
   if bc5x = pos22x then
   if bc5y = pos22y then
   begin eror := 'Des' ; end;

   if bc5x = pos22x then
   if bc5y = pos22y + 25then
   begin eror := 'Des' ; end; end;

   if pos23 = 1 then begin
   if bc5x = pos23x then
   if bc5y = pos23y then
   begin eror := 'Des'; end;

   if bc5x = pos23x + 25 then
   if bc5y = pos23y then
   begin eror := 'Des';end; end;

   if pos23 = 2 then begin
   if bc5x = pos23x then
   if bc5y = pos23y then
   begin eror := 'Des'; end;

   if bc5x = pos23x then
   if bc5y = pos23y + 25 then
   begin eror := 'Des';end; end;

   if bc5x = pos11x then
   if bc5y = pos11y then
   begin eror := 'Des' ; end;

   if bc5x = pos12x then
   if bc5y = pos12y then
   begin eror := 'Des'; end;

   if bc5x = pos13x then
   if bc5y = pos13y then
   begin eror := 'Des' ; end;

   if bc5x = pos14x then
   if bc5y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,55,'warning error in fifth loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,55,'fifth loop Ok');
   Setcolor(White); end; end;

   procedure Check96;
  begin
   if bh6x = pos14x then
   if bh6y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,65,'warning error in sixth loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,65,'third loop Ok');
   Setcolor(White); end; end;

   procedure check86;
  begin
   if bg6x = pos13x then
   if bg6y = pos13y then
   begin eror := 'Des' ; end;

   if bg6x = pos14x then
   if bg6y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,65,'warning error in sixth loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,65,'third loop Ok');
   Setcolor(White); end; end;

   procedure Check76;
  begin
   if bf6x = pos12x then
   if bf6y = pos12y then
   begin eror := 'Des'; end;

   if bf6x = pos13x then
   if bf6y = pos13y then
   begin eror := 'Des' ; end;

   if bf6x = pos14x then
   if bf6y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,65,'warning error in sixth loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,65,'third loop Ok');
   Setcolor(White); end; end;
   procedure Check66;
  begin
    if be6x = pos11x then
   if be6y = pos11y then
   begin eror := 'Des' ; end;

   if be6x = pos12x then
   if be6y = pos12y then
   begin eror := 'Des'; end;

   if be6x = pos13x then
   if be6y = pos13y then
   begin eror := 'Des' ; end;

   if be6x = pos14x then
   if be6y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,65,'warning error in sixth loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,65,'third loop Ok');
   Setcolor(White); end; end;


   procedure Check56;
 begin
 if pos23 = 1 then begin
   if bd6x = pos23x then
   if bd6y = pos23y then
   begin eror := 'Des'; end;

   if bd6x = pos23x + 25 then
   if bd6y = pos23y then
   begin eror := 'Des';end; end;

   if pos23 = 2 then begin
   if bd6x = pos23x then
   if bd6y = pos23y then
   begin eror := 'Des'; end;

   if bd6x = pos23x then
   if bd6y = pos23y + 25 then
   begin eror := 'Des';end; end;

   if bd6x = pos11x then
   if bd6y = pos11y then
   begin eror := 'Des' ; end;

   if bd6x = pos12x then
   if bd6y = pos12y then
   begin eror := 'Des'; end;

   if bd6x = pos13x then
   if bd6y = pos13y then
   begin eror := 'Des' ; end;

   if bd6x = pos14x then
   if bd6y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,65,'warning error in sixth loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,65,'sixth loop Ok');
   Setcolor(White); end; end;

   procedure Check46;
 begin
   if pos22 = 1 then begin
   if bc6x = pos22x then
   if bc6y = pos22y then
   begin eror := 'Des' ; end;

   if bc6x = pos22x + 25 then
   if bc6y = pos22y then
   begin eror := 'Des' ; end; end;

   if pos22 = 2 then begin
   if bc6x = pos22x then
   if bc6y = pos22y then
   begin eror := 'Des' ; end;

   if bc6x = pos22x then
   if bc6y = pos22y + 25then
   begin eror := 'Des' ; end; end;

   if pos23 = 1 then begin
   if bc6x = pos23x then
   if bc6y = pos23y then
   begin eror := 'Des'; end;

   if bc6x = pos23x + 25 then
   if bc6y = pos23y then
   begin eror := 'Des';end; end;

   if pos23 = 2 then begin
   if bc6x = pos23x then
   if bc6y = pos23y then
   begin eror := 'Des'; end;

   if bc6x = pos23x then
   if bc6y = pos23y + 25 then
   begin eror := 'Des';end; end;

   if bc6x = pos11x then
   if bc6y = pos11y then
   begin eror := 'Des' ; end;

   if bc6x = pos12x then
   if bc6y = pos12y then
   begin eror := 'Des'; end;

   if bc6x = pos13x then
   if bc6y = pos13y then
   begin eror := 'Des' ; end;

   if bc6x = pos14x then
   if bc6y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,65,'warning error in sixth loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,65,'sixth loop Ok');
   Setcolor(White); end; end;

   procedure Check97;
  begin
   if bh7x = pos14x then
   if bh7y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,75,'warning error in seventh loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,75,'seventh loop Ok');
   Setcolor(White); end; end;

   procedure Check87;
  begin
   if bg7x = pos13x then
   if bg7y = pos13y then
   begin eror := 'Des' ; end;

   if bg7x = pos14x then
   if bg7y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,75,'warning error in seventh loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,75,'seventh loop Ok');
   Setcolor(White); end; end;

   procedure Check77;
 begin
   if bf7x = pos12x then
   if bf7y = pos12y then
   begin eror := 'Des'; end;

   if bf7x = pos13x then
   if bf7y = pos13y then
   begin eror := 'Des' ; end;

   if bf7x = pos14x then
   if bf7y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,75,'warning error in seventh loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,75,'seventh loop Ok');
   Setcolor(White); end; end;

   procedure Check67;
 begin
   if be7x = pos11x then
   if be7y = pos11y then
   begin eror := 'Des' ; end;

   if be7x = pos12x then
   if be7y = pos12y then
   begin eror := 'Des'; end;

   if be7x = pos13x then
   if be7y = pos13y then
   begin eror := 'Des' ; end;

   if be7x = pos14x then
   if be7y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,75,'warning error in seventh loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,75,'seventh loop Ok');
   Setcolor(White); end; end;

   procedure Check57;
 begin
   if pos23 = 1 then begin
   if bd7x = pos23x then
   if bd7y = pos23y then
   begin eror := 'Des'; end;

   if bd7x = pos23x + 25 then
   if bd7y = pos23y then
   begin eror := 'Des';end; end;

   if pos23 = 2 then begin
   if bd7x = pos23x then
   if bd7y = pos23y then
   begin eror := 'Des'; end;

   if bd7x = pos23x then
   if bd7y = pos23y + 25 then
   begin eror := 'Des';end; end;

   if bd7x = pos11x then
   if bd7y = pos11y then
   begin eror := 'Des' ; end;

   if bd7x = pos12x then
   if bd7y = pos12y then
   begin eror := 'Des'; end;

   if bd7x = pos13x then
   if bd7y = pos13y then
   begin eror := 'Des' ; end;

   if bd7x = pos14x then
   if bd7y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,75,'warning error in seventh loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,75,'seventh loop Ok');
   Setcolor(White); end; end;

   procedure Check47;
 begin
   if pos22 = 1 then begin
   if bc7x = pos22x then
   if bc7y = pos22y then
   begin eror := 'Des' ; end;

   if bc7x = pos22x + 25 then
   if bc7y = pos22y then
   begin eror := 'Des' ; end; end;

   if pos22 = 2 then begin
   if bc7x = pos22x then
   if bc7y = pos22y then
   begin eror := 'Des' ; end;

   if bc7x = pos22x then
   if bc7y = pos22y + 25then
   begin eror := 'Des' ; end; end;

   if pos23 = 1 then begin
   if bc7x = pos23x then
   if bc7y = pos23y then
   begin eror := 'Des'; end;

   if bc7x = pos23x + 25 then
   if bc7y = pos23y then
   begin eror := 'Des';end; end;

   if pos23 = 2 then begin
   if bc7x = pos23x then
   if bc7y = pos23y then
   begin eror := 'Des'; end;

   if bc7x = pos23x then
   if bc7y = pos23y + 25 then
   begin eror := 'Des';end; end;

   if bc7x = pos11x then
   if bc7y = pos11y then
   begin eror := 'Des' ; end;

   if bc7x = pos12x then
   if bc7y = pos12y then
   begin eror := 'Des'; end;

   if bc7x = pos13x then
   if bc7y = pos13y then
   begin eror := 'Des' ; end;

   if bc7x = pos14x then
   if bc7y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,75,'warning error in seventh loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,75,'seventh loop Ok');
   Setcolor(White); end; end;

   procedure Check98;
  begin
   if bh8x = pos14x then
   if bh8y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,85,'warning error in eighth loop!!');
   ReaDLn; halt; end;

     if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,145,'tenth loop Ok');
   Setcolor(White); end;
   OuttextXY(15,155,'Ship test complited,');
   OutTextXY(15,165,' succesfully!');
   OutTextXY(330,300,'Completed');
   SetColor(Yellow);
   OutTextXY(330,325,'Testing ship eight finished!');
   Bar3d(550,455,575,480,4,True);
   Bar3d(600,455,625,480,4,True);
   SetColor(LightGray);
   Bar(11,11,249,449);  end;


   procedure Check88;
  begin
   if bg8x = pos13x then
   if bg8y = pos13y then
   begin eror := 'Des' ; end;

   if bg8x = pos14x then
   if bg8y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,85,'warning error in eighth loop!!');
   ReaDLn; halt; end;

     if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,145,'tenth loop Ok');
   Setcolor(White); end;
   OuttextXY(15,155,'Ship test complited,');
   OutTextXY(15,165,' succesfully!');
   OutTextXY(330,260,'Completed');
   SetColor(Yellow);
   OutTextXY(330,275,'Testing ship nine!');
   Bar3d(500,455,525,480,4,True);
   SetColor(LightGray);
   Bar(11,11,249,449);  end;

   procedure Check78;
  begin
   if bf8x = pos12x then
   if bf8y = pos12y then
   begin eror := 'Des'; end;

   if bf8x = pos13x then
   if bf8y = pos13y then
   begin eror := 'Des' ; end;

   if bf8x = pos14x then
   if bf8y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,85,'warning error in eighth loop!!');
   ReaDLn; halt; end;

     if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,145,'tenth loop Ok');
   Setcolor(White); end;
   OuttextXY(15,155,'Ship test complited,');
   OutTextXY(15,165,' succesfully!');
   OutTextXY(330,230,'Completed');
   SetColor(Yellow);
   OutTextXY(330,245,'Testing ship eigth!');
   Bar3d(450,455,475,480,4,True);
   SetColor(LightGray);
   Bar(11,11,249,449);  end;
   procedure Check68;
  begin
   if be8x = pos11x then
   if be8y = pos11y then
   begin eror := 'Des' ; end;

   if be8x = pos12x then
   if be8y = pos12y then
   begin eror := 'Des'; end;

   if be8x = pos13x then
   if be8y = pos13y then
   begin eror := 'Des' ; end;

   if be8x = pos14x then
   if be8y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,85,'warning error in eighth loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,85,'eigth loop Ok');
   Setcolor(White); end; end;

   procedure Check58;
 begin
   if pos23 = 1 then begin
   if bd8x = pos23x then
   if bd8y = pos23y then
   begin eror := 'Des'; end;

   if bd8x = pos23x + 25 then
   if bd8y = pos23y then
   begin eror := 'Des';end; end;

   if pos23 = 2 then begin
   if bd8x = pos23x then
   if bd8y = pos23y then
   begin eror := 'Des'; end;

   if bd8x = pos23x then
   if bd8y = pos23y + 25 then
   begin eror := 'Des';end; end;

   if bd8x = pos11x then
   if bd8y = pos11y then
   begin eror := 'Des' ; end;

   if bd8x = pos12x then
   if bd8y = pos12y then
   begin eror := 'Des'; end;

   if bd8x = pos13x then
   if bd8y = pos13y then
   begin eror := 'Des' ; end;

   if bd8x = pos14x then
   if bd8y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,85,'warning error in eighth loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,85,'eigth loop Ok');
   Setcolor(White); end; end;

   procedure Check48;
 begin
   if pos22 = 1 then begin
   if bc8x = pos22x then
   if bc8y = pos22y then
   begin eror := 'Des' ; end;

   if bc8x = pos22x + 25 then
   if bc8y = pos22y then
   begin eror := 'Des' ; end; end;

   if pos22 = 2 then begin
   if bc8x = pos22x then
   if bc8y = pos22y then
   begin eror := 'Des' ; end;

   if bc8x = pos22x then
   if bc8y = pos22y + 25then
   begin eror := 'Des' ; end; end;

   if pos23 = 1 then begin
   if bc8x = pos23x then
   if bc8y = pos23y then
   begin eror := 'Des'; end;

   if bc8x = pos23x + 25 then
   if bc8y = pos23y then
   begin eror := 'Des';end; end;

   if pos23 = 2 then begin
   if bc8x = pos23x then
   if bc8y = pos23y then
   begin eror := 'Des'; end;

   if bc8x = pos23x then
   if bc8y = pos23y + 25 then
   begin eror := 'Des';end; end;

   if bc8x = pos11x then
   if bc8y = pos11y then
   begin eror := 'Des' ; end;

   if bc8x = pos12x then
   if bc8y = pos12y then
   begin eror := 'Des'; end;

   if bc8x = pos13x then
   if bc8y = pos13y then
   begin eror := 'Des' ; end;

   if bc8x = pos14x then
   if bc8y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,85,'warning error in eighth loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,85,'eigth loop Ok');
   Setcolor(White); end; end;

    procedure Check69;
   begin
   if be9x = pos11x then
   if be9y = pos11y then
   begin eror := 'Des' ; end;

   if be9x = pos12x then
   if be9y = pos12y then
   begin eror := 'Des'; end;

   if be9x = pos13x then
   if be9y = pos13y then
   begin eror := 'Des' ; end;

   if be9x = pos14x then
   if be9y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,95,'warning error in nineth loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,95,'nineth loop Ok');
   Setcolor(White); end; end;



    procedure Check59;
 begin
    if pos23 = 1 then begin
   if bd9x = pos23x then
   if bd9y = pos23y then
   begin eror := 'Des'; end;

   if bd9x = pos23x + 25 then
   if bd9y = pos23y then
   begin eror := 'Des';end; end;

   if pos23 = 2 then begin
   if bd9x = pos23x then
   if bd9y = pos23y then
   begin eror := 'Des'; end;

   if bd9x = pos23x then
   if bd9y = pos23y + 25 then
   begin eror := 'Des';end; end;

   if bd9x = pos11x then
   if bd9y = pos11y then
   begin eror := 'Des' ; end;

   if bd9x = pos12x then
   if bd9y = pos12y then
   begin eror := 'Des'; end;

   if bd9x = pos13x then
   if bd9y = pos13y then
   begin eror := 'Des' ; end;

   if bd9x = pos14x then
   if bd9y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,95,'warning error in nineth loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,95,'nineth loop Ok');
   Setcolor(White); end; end;

    procedure Check49;
  begin
   if pos22 = 1 then begin
   if bc9x = pos22x then
   if bc9y = pos22y then
   begin eror := 'Des' ; end;

   if bc9x = pos22x + 25 then
   if bc9y = pos22y then
   begin eror := 'Des' ; end; end;

   if pos22 = 2 then begin
   if bc9x = pos22x then
   if bc9y = pos22y then
   begin eror := 'Des' ; end;

   if bc9x = pos22x then
   if bc9y = pos22y + 25then
   begin eror := 'Des' ; end; end;

   if pos23 = 1 then begin
   if bc9x = pos23x then
   if bc9y = pos23y then
   begin eror := 'Des'; end;

   if bc9x = pos23x + 25 then
   if bc9y = pos23y then
   begin eror := 'Des';end; end;

   if pos23 = 2 then begin
   if bc9x = pos23x then
   if bc9y = pos23y then
   begin eror := 'Des'; end;

   if bc9x = pos23x then
   if bc9y = pos23y + 25 then
   begin eror := 'Des';end; end;

   if bc9x = pos11x then
   if bc9y = pos11y then
   begin eror := 'Des' ; end;

   if bc9x = pos12x then
   if bc9y = pos12y then
   begin eror := 'Des'; end;

   if bc9x = pos13x then
   if bc9y = pos13y then
   begin eror := 'Des' ; end;

   if bc9x = pos14x then
   if bc9y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,95,'warning error in nineth loop!!');
   ReaDLn; halt; end;

   if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,95,'nineth loop Ok');
   Setcolor(White); end; end;

   procedure Check610;
  begin
   if be10x = pos11x then
   if be10y = pos11y then
   begin eror := 'Des' ; end;

   if be10x = pos12x then
   if be10y = pos12y then
   begin eror := 'Des'; end;

   if be10x = pos13x then
   if be10y = pos13y then
   begin eror := 'Des' ; end;

   if be10x = pos14x then
   if be10y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,105,'warning error in tenth loop!!');
   ReaDLn; halt; end;

    if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,145,'tenth loop Ok');
   Setcolor(White); end;
   OuttextXY(15,155,'Ship test complited,');
   OutTextXY(15,165,' succesfully!');
   OutTextXY(330,200,'Completed');
   SetColor(Yellow);
   OutTextXY(330,215,'Testing ship seven!');
   Bar3d(405,455,430,480,4,True);
   SetColor(LightGray);
   Bar(11,11,249,449);  end;

   procedure Check510;
 begin
     if pos23 = 1 then begin
   if bd10x = pos23x then
   if bd10y = pos23y then
   begin eror := 'Des'; end;

   if bd10x = pos23x + 25 then
   if bd10y = pos23y then
   begin eror := 'Des';end; end;

   if pos23 = 2 then begin
   if bd10x = pos23x then
   if bd10y = pos23y then
   begin eror := 'Des'; end;

   if bd10x = pos23x then
   if bd10y = pos23y + 25 then
   begin eror := 'Des';end; end;

   if bd10x = pos11x then
   if bd10y = pos11y then
   begin eror := 'Des' ; end;

   if bd10x = pos12x then
   if bd10y = pos12y then
   begin eror := 'Des'; end;

   if bd10x = pos13x then
   if bd10y = pos13y then
   begin eror := 'Des' ; end;

   if bd10x = pos14x then
   if bd10y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,105,'warning error in tenth loop!!');
   ReaDLn; halt; end;

    if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,145,'tenth loop Ok');
   Setcolor(White); end;
   OuttextXY(15,155,'Ship test complited,');
   OutTextXY(15,165,' succesfully!');
   OutTextXY(330,160,'Completed');
   SetColor(Yellow);
   OutTextXY(330,175,'Testing ship six!');
   Bar3d(355,455,380,480,4,True);
   SetColor(LightGray);
   Bar(11,11,249,449);  end;

   procedure Check410;
 begin
    if pos22 = 1 then begin
   if bc10x = pos22x then
   if bc10y = pos22y then
   begin eror := 'Des' ; end;

   if bc10x = pos22x + 25 then
   if bc10y = pos22y then
   begin eror := 'Des' ; end; end;

   if pos22 = 2 then begin
   if bc10x = pos22x then
   if bc10y = pos22y then
   begin eror := 'Des' ; end;

   if bc10x = pos22x then
   if bc10y = pos22y + 25then
   begin eror := 'Des' ; end; end;

   if pos23 = 1 then begin
   if bc10x = pos23x then
   if bc10y = pos23y then
   begin eror := 'Des'; end;

   if bc10x = pos23x + 25 then
   if bc10y = pos23y then
   begin eror := 'Des';end; end;

   if pos23 = 2 then begin
   if bc10x = pos23x then
   if bc10y = pos23y then
   begin eror := 'Des'; end;

   if bc10x = pos23x then
   if bc10y = pos23y + 25 then
   begin eror := 'Des';end; end;

   if bc10x = pos11x then
   if bc10y = pos11y then
   begin eror := 'Des' ; end;

   if bc10x = pos12x then
   if bc10y = pos12y then
   begin eror := 'Des'; end;

   if bc10x = pos13x then
   if bc10y = pos13y then
   begin eror := 'Des' ; end;

   if bc10x = pos14x then
   if bc10y = pos14y then
   begin eror := 'Des' ; end;

   if eror = 'Des' then begin
   SetColor(LightRed);
   outTextXY(15,105,'warning error in tenth loop!!');
   ReaDLn; halt; end;

    if eror <> 'Des' then begin
   SetColor(LightBlue);
   OutTextXY(15,145,'twelfth loop Ok');
   Setcolor(White); end;
   OuttextXY(15,155,'Ship two test complited,');
   OutTextXY(15,165,' succesfully!');
   OutTextXY(330,130,'Completed');
   SetColor(Yellow);
   OutTextXY(330,145,'Testing ship five!');
   Bar3d(305,455,330,480,4,True);
   SetColor(LightGray);
   Bar(11,11,249,449);  end; end.
